config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'pages/about'
  get "pages/manhattan"
  get "pages/brooklyn"
  get "pages/queens"
  get "pages/the_bronx"
  get "pages/staten_island"
  
    get "manhattan" => "pages#manhattan"
    get "brooklyn" => "pages#brooklyn"
    get "queens" => "pages#queens"
    get "the_bronx" => "pages#the_bronx"
    get "staten_island" => "pages#staten_island"
    get "about" => "pages#about"

  root "pages#home" 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def manhattan
  end

  def brooklyn
  end

  def the_bronx
  end

  def queens
  end

  def staten_island
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NYC Burger</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= link_to "Home", root_path %>
<%= link_to "Manhattan", manhattan_path %>
<%= link_to "Brooklyn", brooklyn_path %>
<%= link_to "Queens", queens_path %>
<%= link_to "The Bronx", the_bronx_path %>
<%= link_to "Staten Island", staten_island_path %>
<%= link_to "About", about_path %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About NYC Burger</h1>
<p>We point you in the direction of getting the best buger no matter where you are in NYC</p>

app/views/pages/brooklyn.html.erb
<H1>Welcome to Brooklyn</H1>	

app/views/pages/home.html.erb
<h1>Welcome to NYC Burger</h1>
<p>Sign Up Here <%= link_to "here", "#" %></p>

app/views/pages/manhattan.html.erb
<h1> Welcome to Manhattan </h1>

app/views/pages/queens.html.erb
<H1>Welcome to Queens</H1>	

app/views/pages/staten_island.html.erb
<h1> Welcome to Staten Island</h1>

app/views/pages/the_bronx.html.erb
<h1> Welcome to The Bronx</h1>